### ISSUE TITLE
Seting sebagai pengurus desa

### ISSUE THREAD

**Issue by Aasubandoyo** [wakca/sosmed#4]
1. Pada saat "set pengguna" muncul kotak pertanyaan "hapus user" apakah yakin ingin menjadikan user ini sebagai pengurus desa sukagalih?
Ya (logo tempat sampah)
2. Setelah ya.. maka muncul otomatis tanda pengurus centang di kolom username (sudah good)
3. Setelah jadi pengurus, misalnya dia pindah desa, sebaiknya kita bisa jadi "user  biasa" kan sudah pindah, atau misalnya melakukan hal tidak betul sehingga kewenangan "pengurusnya" kita cabut
..itu jadi judulnya saja masih "hapus user" dan ikonnya masih "kotak sampah"

**Comment by antoniosai** [comment]
Solved at https://github.com/wakca/sosmed/commit/2501ad1bd1b523f2b6381febea656d34785f747d
